from __future__ import annotations

from typing import Protocol

from aipm.models.events import Event
from aipm.models.incidents import Incident, IncidentFilter


class IncidentRepository(Protocol):
    def initialize(self) -> None: ...

    def get_open_by_correlation(self, correlation_key: str) -> Incident | None: ...

    def apply_event(self, event: Event, *, opens_incident: bool, resolves_incident: bool) -> Incident | None: ...

    def acknowledge(self, incident_id: int, acknowledged_at) -> Incident | None: ...

    def get_incidents(self, incident_filter: IncidentFilter) -> list[Incident]: ...

    def get_incidents_page(self, incident_filter: IncidentFilter, *, before: tuple[object, int] | None = None) -> list[Incident]: ...

    def get_timeline(self, incident_id: int, *, limit: int, after: tuple[object, int] | None = None) -> list[dict[str, object]]: ...

    def get_incident(self, incident_id: int) -> Incident | None: ...

    def delete_old_resolved(self, cutoff) -> int: ...
