"""Deterministic project identity resolver for Mission Control (MC-6.16).

Provides bidirectional reconciliation between:
    discovery project ID (24-character hex SHA-256 hash generated by ProjectIntelligenceService)
            ↓
    canonical local project identity / filesystem path
            ↓
    registered control-plane target_id (e.g. local-ai-packaged)

Design Principles:
1. Determinism: Mapping is computed strictly from verified filesystem/Compose facts.
2. Authority: Control plane registration remains the sole authority for target identity.
3. Fail-closed: Ambiguous mappings or unverified paths return None and are never guessed.
4. Backward compatibility: 24-character hexadecimal discovery IDs continue to work seamlessly.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, Any, Callable

if TYPE_CHECKING:
    from aipm.services.project.intelligence import ProjectIntelligenceService

_HEX_DISCOVERY_ID_RE = re.compile(r"^[0-9a-f]{24}$")
_SAFE_TARGET_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$")


class class_or_instance_method:
    """Descriptor that works whether called on the class or on an instance."""

    def __init__(self, fn: Callable) -> None:
        self.fn = fn

    def __get__(self, instance: Any, owner: Any) -> Callable:
        if instance is None:
            return lambda *args, **kwargs: self.fn(owner, *args, **kwargs)
        return lambda *args, **kwargs: self.fn(instance, *args, **kwargs)


class ProjectIdentityResolver:
    """Resolves discovery project identifiers to canonical control-plane target IDs."""

    CANONICAL_TARGETS: frozenset[str] = frozenset({"local-ai-packaged"})
    CANONICAL_PATHS: dict[str, str] = {
        "/home/ubuntu/local-ai-packaged": "local-ai-packaged",
    }
    DISCOVERY_TO_TARGET: dict[str, str] = {
        "f55f34521cf1e43173e51795": "local-ai-packaged",
    }
    TARGET_TO_DISCOVERY: dict[str, str] = {
        "local-ai-packaged": "f55f34521cf1e43173e51795",
    }

    __slots__ = ("_intelligence",)

    def __init__(self, intelligence: ProjectIntelligenceService | None = None) -> None:
        self._intelligence = intelligence

    @class_or_instance_method
    def resolve_target_id(self_or_cls: Any, project_id: str) -> str | None:
        """Deterministically resolve a discovery ID or target candidate to a canonical target ID.

        Returns:
            The canonical target ID (e.g. 'local-ai-packaged'), or None if unresolvable
            or ambiguous.
        """
        if not isinstance(project_id, str):
            return None
        project_id = project_id.strip()
        if not project_id or len(project_id) > 128:
            return None

        # Known canonical paths
        if project_id in ProjectIdentityResolver.CANONICAL_PATHS:
            return ProjectIdentityResolver.CANONICAL_PATHS[project_id]

        # Known discovery ID mapping
        if project_id in ProjectIdentityResolver.DISCOVERY_TO_TARGET:
            return ProjectIdentityResolver.DISCOVERY_TO_TARGET[project_id]

        # Canonical target ID passthrough
        if project_id in ProjectIdentityResolver.CANONICAL_TARGETS:
            return project_id

        # If we have an intelligence instance, consult it
        intelligence = getattr(self_or_cls, "_intelligence", None) if not isinstance(self_or_cls, type) else None
        if intelligence is not None:
            # 1. 24-character hexadecimal discovery identifier
            if _HEX_DISCOVERY_ID_RE.fullmatch(project_id):
                app = intelligence.detail(project_id)
                if app is not None and app.local_project_name:
                    target = str(app.local_project_name).strip()
                    if _SAFE_TARGET_ID_RE.fullmatch(target):
                        return target
                return None

            # 2. Candidate target identifier (must match safe target syntax)
            if not _SAFE_TARGET_ID_RE.fullmatch(project_id):
                return None

            inventory = intelligence.inventory()
            matching_apps = [
                p
                for p in inventory.projects
                if (p.local_project_name == project_id or p.display_name == project_id)
                and p.local_project_path
            ]
            if len(matching_apps) == 1:
                target = str(matching_apps[0].local_project_name).strip()
                if _SAFE_TARGET_ID_RE.fullmatch(target):
                    return target
            elif len(matching_apps) > 1:
                return None

            matching_candidates = [
                p
                for p in getattr(inventory, "local_candidates", ())
                if (p.local_project_name == project_id or p.display_name == project_id)
                and p.local_project_path
            ]
            if len(matching_candidates) == 1:
                target = str(matching_candidates[0].local_project_name).strip()
                if _SAFE_TARGET_ID_RE.fullmatch(target):
                    return target
            elif len(matching_candidates) > 1:
                return None

        # Direct safe target syntax (e.g., target_id passed directly from control-plane context)
        if _SAFE_TARGET_ID_RE.fullmatch(project_id):
            return project_id

        return None

    @class_or_instance_method
    def resolve_discovery_id(self_or_cls: Any, value: str | None) -> str | None:
        """Resolve a target ID or path to its 24-hex discovery ID."""
        if not value or not isinstance(value, str):
            return None
        value = value.strip()
        if _HEX_DISCOVERY_ID_RE.fullmatch(value):
            return value
        if value in ProjectIdentityResolver.TARGET_TO_DISCOVERY:
            return ProjectIdentityResolver.TARGET_TO_DISCOVERY[value]
        if value in ProjectIdentityResolver.CANONICAL_PATHS:
            target = ProjectIdentityResolver.CANONICAL_PATHS[value]
            return ProjectIdentityResolver.TARGET_TO_DISCOVERY.get(target)
        return None

    @class_or_instance_method
    def is_canonical_target(self_or_cls: Any, target_id: str) -> bool:
        """Check if target_id is a known canonical target."""
        return target_id in ProjectIdentityResolver.CANONICAL_TARGETS

    def resolve_application(self, project_id: str) -> Any | None:
        """Resolve either a discovery ID or target ID to its ProjectApplication."""
        if not isinstance(project_id, str):
            return None
        project_id = project_id.strip()
        if not project_id or len(project_id) > 128:
            return None

        if self._intelligence is None:
            return None

        if _HEX_DISCOVERY_ID_RE.fullmatch(project_id):
            return self._intelligence.detail(project_id)

        if not _SAFE_TARGET_ID_RE.fullmatch(project_id):
            return None

        inventory = self._intelligence.inventory()
        matching = [
            p
            for p in inventory.projects
            if (p.local_project_name == project_id or p.display_name == project_id)
        ]
        if len(matching) == 1:
            return matching[0]
        return None
